// frontend/src/app/pages/character/character.component.ts
import { Component, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import Character from '../../types/character';
import { characters } from '../../placeholders/placeholders';

@Component({
  selector: 'app-character',
  templateUrl: './character.component.html',
  styleUrl: './character.component.scss'
})
export class CharacterPage {
  charId:string="";
  character?:Character;
  private activeRoute = inject(ActivatedRoute);

  constructor(){
    this.activeRoute.params.subscribe(params=>{
      this.charId = params['charId'];
      this.character = characters.find(char=>char.id==parseInt(this.charId));
    })
  }
}

<h1>Hello, {{character?.name}}</h1>
<h3>created by {{character?.creator}}</h3>
<p>{{character?.description}}</p>

// frontend/app/pages/character.tsx
import { characters } from "~/placeholders";
import type {Route} from "../+types/root"

export function meta({}:Route.MetaArgs){
    return[
        {title:"Character"}
    ];
}
export default function Character({params}:Route.ComponentProps){
    let character = characters.find(character=>params.id&&character.id==parseInt(params.id));
    return <><h1>Hello {character?.name}</h1></>
}
