// frontend/src/app/pages/story/story.component.ts
import { Component, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import Story from '../../types/story';
import { stories } from '../../placeholders/placeholders';

@Component({
  selector: 'app-story',
  templateUrl: './story.component.html',
  styleUrl: './story.component.scss'
})
export class StoryPage {
  storyId:string = "";
  story?:Story;
  private activatedRoute = inject(ActivatedRoute);

  constructor(){
    this.activatedRoute.params.subscribe(param=>{
      this.storyId = param["storyId"];
      this.story = stories.find(story=>story.id==parseInt(this.storyId));
    })
  }
}

<H1>This is {{story?.title}}</H1>
<h3>by {{story?.creator}}</h3>
<p>{{story?.description}}</p>

// frontend/app/pages/story.tsx
import { stories } from "~/placeholders";
import type { Route } from "../+types/root";

export default function Story({params}:Route.ComponentProps){
    let story = stories.find(story=>params.id&&story.id==parseInt(params.id))
    
    return <>
        <h1>This is {story?.title}</h1> 
        <h3>by {story?.creator}</h3>
    </>
}
