// frontend/src/app/components/page-components/story-thumbnail/story-thumbnail.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from "@angular/router";
import Story from '../../../types/story';

@Component({
  selector: 'story-thumbnail',
  templateUrl: './story-thumbnail.component.html',
  styleUrl: './story-thumbnail.component.scss'
})
export class StoryThumbnailComponent {
  @Input({required:true})story!:Story;
  get title(){
    return this.story.title;
  }
  get creator(){
    return this.story.creator;
  }
}

<a routerLink="/" class="storythumbnail">
    <img src="../../assets/Deadly laser.jpg" alt="nothing" />
    <h1 className="title">{{title}}</h1>
    <h3 className="creator">{{creator}}</h3>
</a>

// frontend/app/components/storyThumbnail.tsx
import { NavLink } from "react-router";

export default function StoryThumbnail({title, creator, id}:Story){
    return <NavLink to={`/story/${id}`}>
        <div className="storythumbnail">
            <img src="/Deadly laser.jpg" alt="nothing" />
            <h1 className="title">{title}</h1>
            <h3 className="creator">{creator}</h3>
        </div>
    </NavLink>
}
