// frontend/src/app/pages/sign-in/sign-in.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'sign-in-page',
  templateUrl: './sign-in.component.html',
  styleUrl: './sign-in.component.scss'
})
export class SignInPage {

}

<form>
    <label htmlFor="username">Username</label><input type="text" id="username"/>
    <label htmlFor="email">Email</label><input type="text" id="email"/>
    <label htmlFor="password">Password</label><input type="password" name="" id="password" />
    <label htmlFor="rePass">Repeat Password</label><input type="password" name="" id="rePass" />
    <input type="submit" value="Sign In" id="submit"/>
</form>
<p>Already have an account? <a routerLink="/login">Log in.</a></p>

// frontend-old/app/pages/signIn.tsx
export default function SignIn(){
    return <form>
       <label htmlFor="username">Username</label><input type="text" id="username"/>
       <label htmlFor="email">Email</label><input type="text" id="email"/>
        <label htmlFor="password">Password</label><input type="password" name="" id="password" />
        <label htmlFor="rePass">Repeat Password</label><input type="password" name="" id="rePass" />
        <input type="submit" value="Sign In" id="submit"/>
    </form>
}
