// frontend-old/app/components/characterThumbnail.tsx
import React from "react"
import { NavLink } from "react-router"

export default function CharacterThumbnail({name, creator, id}:Character){
    return <NavLink to={`/character/${id}`}>
                <div className="charthumbnail">
                    <img src="/character.svg" alt="" className="picture"/>
                    <div className="info">
                        <h1>{name}</h1>
                        <h3>{creator}</h3>
                    </div>
                </div>        
            </NavLink>
        
    
}//https://www.netjstech.com/2025/06/using-navlink-in-react-router.html

// frontend/src/app/components/page-components/character-thumbnail/character-thumbnail.component.ts
import { Component, Input } from '@angular/core';
import Character from '../../../types/character';

@Component({
  selector: 'character-thumbnail',
  templateUrl: './character-thumbnail.component.html',
  styleUrl: './character-thumbnail.component.scss'
})
export class CharacterThumbnailComponent {
  @Input({required:true}) character!:Character;
}

<a [routerLink]="['character', character.id]" class="charthumbnail">
    <img src="../../assets/character.svg" alt="thing" class="picture">
    <div class="info">
        <h1>{{name}}</h1>
        <h3>{{creator}}</h3>
    </div>
</a>
