// frontend/app/components/checkbox.tsx
import type { ChangeEventHandler } from "react";

export default function Checkbox({name, id, label, checked, onCheck, enabled}:{name:string, id:string, label:string, checked:boolean, onCheck:ChangeEventHandler, enabled?:boolean}){
return <>
        <input type="checkbox" name={name} id={id} checked={checked} onChange={e=>onCheck(e)} disabled={!enabled}/> 
        <label htmlFor={id}>{label}</label>
    </>
}

// frontend/src/app/components/page-components/checkbox/checkbox.component.ts
import { Component, Input, model } from '@angular/core';

@Component({
  selector: 'checkbox',
  templateUrl: './checkbox.component.html',
  styleUrl: './checkbox.component.scss'
})
export class CheckboxComponent {
  @Input({required:true})name:string=""
  @Input()enabled:boolean=true;
  checked=model<boolean>(true);
}

<input type="checkbox" name="{{name}}" id="{{name}}" [(ngModel)]="checked" disabled={{!enabled}}>
<label for="{{name}}">{{name}}</label>
