// frontend/app/pages/login.tsx
export default function Login(){
    return <form>
        <label htmlFor="username">Username</label><input type="text" id="username"/>
        <label htmlFor="password">Password</label><input type="password" name="" id="password" />
        <input type="submit" value="Log In" id="submit" />
    </form>
}

// frontend/src/app/pages/log-in/log-in.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-log-in',
  templateUrl: './log-in.component.html',
  styleUrl: './log-in.component.scss',
})
export class LogInPage {

}

<form>
    <label htmlFor="username">Username</label><input type="text" id="username"/>
    <label htmlFor="password">Password</label><input type="password" name="" id="password" />
    <input type="submit" value="Log In" id="submit" />
</form>

<p>Don't have an account? <a routerLink="/signin">Sign in.</a></p>
